export const GET_REPORT = 'GET_REPORT';
export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
export const GET_REPORT_EMPTY = 'GET_REPORT_EMPTY';
export const GET_REPORT_FAILED = 'GET_REPORT_FAILED';
export const CLEAR_REPORT_ERRORS = 'CLEAR_REPORT_ERRORS';
export const CLEAR_REPORT_WARNINGS = 'CLEAR_REPORT_WARNINGS';
export const UPDATE_COMING_SOON_HOURS = 'UPDATE_COMING_SOON_HOURS';
export const UPDATE_COMING_SOON_HOURS_SUCCESS = 'UPDATE_COMING_SOON_HOURS_SUCCESS';
export const UPDATE_COMING_SOON_HOURS_FAILURE = 'UPDATE_COMING_SOON_HOURS_FAILURE';


export const GET_IDEAS = 'GET_IDEAS';
export const GET_IDEAS_SUCCESS = 'GET_IDEAS_SUCCESS';
export const GET_IDEAS_FAILED = 'GET_IDEAS_FAILED';

export const ADD_IDEA = 'ADD_IDEA';
export const ADD_IDEA_SUCCESS = 'ADD_IDEA_SUCCESS';
export const ADD_IDEA_FAILED = 'ADD_IDEA_FAILED';

