export const GET_IDEAS = 'GET_IDEAS';
export const GET_IDEAS_SUCCESS = 'GET_IDEAS_SUCCESS';
export const GET_IDEAS_FAILED = 'GET_IDEAS_FAILED';

export const ADD_IDEA = 'ADD_IDEA';
export const ADD_IDEA_SUCCESS = 'ADD_IDEA_SUCCESS';
export const ADD_IDEA_FAILED = 'ADD_IDEA_FAILED';

export const DELETE_IDEA = 'DELETE_IDEA';
export const DELETE_IDEA_SUCCESS = 'DELETE_IDEA_SUCCESS';
export const DELETE_IDEA_FAILED = 'UPDATE_IDEA_FAILED';

export const UPDATE_IDEA = 'UPDATE_BODY';
export const UPDATE_IDEA_SUCCESS = 'UPDATE_IDEA_SUCCESS';
export const UPDATE_IDEA_FAILED = 'UPDATE_IDEA_FAILED';

export const  CHANGE_IDEA_TITLE ='CHANGE_IDEA_TITLE';
export const  CHANGE_IDEA_BODY ='CHANGE_IDEA_BODY';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';


